version: "3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3003:3000"
    volumes: 
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: mongo

  proxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app:app
